# Generated by Django 4.0.4 on 2022-09-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitems',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitems',
            name='quantity',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
