# Generated by Django 4.0.4 on 2022-09-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measure',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
