# Generated by Django 4.0.4 on 2022-09-07 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0003_newregister'),
        ('foodservice', '0002_product_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrand',
            name='brand',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='ProductMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.CharField(max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='default.company')),
            ],
            options={
                'verbose_name': 'Unidade de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foodservice.productmeasure'),
        ),
    ]
