# Generated by Django 4.0.4 on 2022-09-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodservice', '0002_sale_delivery_sale_delivery_cost_sale_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
