# Generated by Django 4.0.4 on 2022-09-08 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0003_newregister'),
        ('foodservice', '0003_alter_productbrand_brand_productmeasure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='company_worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='default.companyworker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmeasure',
            name='company_worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='default.companyworker'),
            preserve_default=False,
        ),
    ]
