# Generated by Django 4.0.4 on 2022-09-13 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodservice', '0003_sale_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitems',
            name='sale',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='foodservice.sale'),
        ),
    ]
