# Generated by Django 4.0.4 on 2022-09-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodservice', '0004_saleitems_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitems',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='saleitems',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
