# Generated by Django 4.0.4 on 2022-09-13 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodservice', '0005_alter_saleitems_price_alter_saleitems_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitems',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foodservice.sale'),
        ),
    ]
