# Generated by Django 4.0.4 on 2022-09-15 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodservice', '0006_alter_saleitems_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='delivery',
        ),
    ]
