# Generated by Django 4.0.4 on 2022-09-15 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodservice', '0007_remove_sale_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='delivery_cost',
            new_name='delivery',
        ),
    ]
