# Generated by Django 4.0.4 on 2022-09-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodservice', '0008_alter_productsaleitems_options_productitems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductItems',
        ),
    ]
