# Generated by Django 4.0.4 on 2022-09-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodservice', '0010_productitems_delete_productsaleitems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSale',
        ),
    ]
