# Generated by Django 4.0.4 on 2022-09-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodservice', '0011_delete_productsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.IntegerField(choices=[('1', 'Consumo'), ('2', 'Revenda')], default=1),
            preserve_default=False,
        ),
    ]
