# Generated by Django 4.0.4 on 2022-09-11 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodservice', '0012_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='foodservice.productbrand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='measure',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='foodservice.productmeasure'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
