# Generated by Django 4.0.4 on 2022-09-11 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodservice', '0015_saleitems_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitems',
            name='product_item',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.PROTECT, related_name='product_items', to='foodservice.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productitems',
            name='quantity',
            field=models.FloatField(default=23),
            preserve_default=False,
        ),
    ]
