# Generated by Django 4.0.4 on 2022-09-02 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('default', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_name', models.CharField(max_length=50)),
                ('corporate_cnpj', models.CharField(max_length=20)),
                ('corporate_ie', models.CharField(max_length=20)),
                ('corporate_email', models.CharField(max_length=50)),
                ('corporate_number', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='default.company')),
                ('company_worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='default.companyworker')),
            ],
            options={
                'verbose_name': 'Customer Company',
                'verbose_name_plural': 'Customers Companys',
                'ordering': ('corporate_name',),
            },
        ),
        migrations.CreateModel(
            name='CustomerCompanyWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_cpf', models.CharField(max_length=20)),
                ('customer_email', models.CharField(max_length=50)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_admin', models.BooleanField(default=False)),
                ('customer_staff', models.BooleanField(default=False)),
                ('customer_normal', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('corporate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suport.customercompany')),
            ],
            options={
                'verbose_name': 'Customer Company Worker',
                'verbose_name_plural': 'Customers Companys Workers',
                'ordering': ('customer_name',),
            },
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_name', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='default.company')),
            ],
            options={
                'verbose_name': 'Request Type',
                'verbose_name_plural': 'Requests Type',
                'ordering': ('company', 'request_name'),
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('routine', models.CharField(max_length=255)),
                ('duty', models.BooleanField(default=False)),
                ('description_problem', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='default.company')),
                ('company_worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='default.companyworker')),
                ('corporate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suport.customercompany')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suport.customercompanyworker')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ('company', 'company_worker', 'title'),
            },
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=127)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='default.company')),
            ],
            options={
                'verbose_name': 'Ticket Status',
                'verbose_name_plural': 'Ticket Status',
                'ordering': ('status', 'company'),
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suport.ticket')),
                ('worker_comment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='default.companyworker')),
            ],
            options={
                'verbose_name': 'Ticket Comment',
                'verbose_name_plural': 'Ticket Comments',
                'ordering': ('ticket', 'created'),
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='suport.ticketstatus'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suport.requesttype'),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('num_card', models.IntegerField(blank=True)),
                ('valid_card', models.DateField(blank=True)),
                ('cvv_card', models.IntegerField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='default.company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ('company', 'name'),
            },
        ),
    ]
