# Generated by Django 4.0.4 on 2022-09-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttype',
            name='request_name',
            field=models.CharField(max_length=30),
        ),
    ]
