# Generated by Django 4.0.4 on 2022-08-26 16:04

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('cnpj', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companys',
                'ordering': ('company',),
            },
        ),
        migrations.CreateModel(
            name='CompanyPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.company')),
            ],
            options={
                'verbose_name': 'Company Position',
                'verbose_name_plural': 'Company Positions',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='CompanyWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.IntegerField()),
                ('rg', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.company')),
            ],
            options={
                'verbose_name': 'Company Worker',
                'verbose_name_plural': 'Company Workers',
                'ordering': ('person',),
            },
        ),
        migrations.CreateModel(
            name='CustomerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_name', models.CharField(max_length=50)),
                ('corporate_cnpj', models.CharField(max_length=20)),
                ('corporate_ie', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.company')),
            ],
            options={
                'verbose_name': 'Customer Company',
                'verbose_name_plural': 'Customers Companys',
                'ordering': ('corporate_name',),
            },
        ),
        migrations.CreateModel(
            name='CustomerCompanyWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_cpf', models.CharField(max_length=16)),
                ('customer_email', models.CharField(max_length=50)),
                ('customer_phone', models.CharField(max_length=11)),
                ('customer_admin', models.BooleanField(default=False)),
                ('customer_staff', models.BooleanField(default=False)),
                ('customer_normal', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('corporate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.customercompany')),
            ],
            options={
                'verbose_name': 'Customer Company Worker',
                'verbose_name_plural': 'Customers Companys Workers',
                'ordering': ('customer_name',),
            },
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_name', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.company')),
            ],
            options={
                'verbose_name': 'Request Type',
                'verbose_name_plural': 'Requests Type',
                'ordering': ('company', 'request_name'),
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('routine', models.CharField(max_length=255)),
                ('duty', models.BooleanField(default=False)),
                ('description_problem', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.company')),
                ('company_worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.companyworker')),
                ('corporate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.customercompany')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.customercompanyworker')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ('company', 'company_worker', 'title'),
            },
        ),
        migrations.CreateModel(
            name='UserProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=127)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.company')),
            ],
            options={
                'verbose_name': 'Ticket Choice',
                'verbose_name_plural': 'Ticket Choices',
                'ordering': ('status', 'company'),
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.ticket')),
                ('worker_comment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.companyworker')),
            ],
            options={
                'verbose_name': 'Ticket Comment',
                'verbose_name_plural': 'Ticket Comments',
                'ordering': ('ticket', 'created'),
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='app.ticketstatus'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.requesttype'),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('num_card', models.IntegerField(blank=True)),
                ('valid_card', models.DateField(blank=True)),
                ('cvv_card', models.IntegerField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.userproxy')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ('company', 'name'),
            },
        ),
        migrations.AddField(
            model_name='companyworker',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.userproxy'),
        ),
        migrations.AddField(
            model_name='companyworker',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.companyposition'),
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.userproxy'),
        ),
    ]
