# Generated by Django 4.0.4 on 2022-08-13 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_companyworkerposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyworker',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.companyposition'),
            preserve_default=False,
        ),
    ]
