# Generated by Django 4.0.4 on 2022-08-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_companyowner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyworker',
            name='phone_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyworker',
            name='rg',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CompanyOwner',
        ),
    ]
