# Generated by Django 4.0.4 on 2022-08-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customercompany_corporate_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercompanyworker',
            name='customer_cpf',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customercompanyworker',
            name='customer_phone',
            field=models.CharField(max_length=20),
        ),
    ]
