# Generated by Django 4.0.4 on 2022-09-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=19),
        ),
        migrations.AlterField(
            model_name='company',
            name='company',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='companyworker',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='companyworker',
            name='phone_number',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='companyworker',
            name='rg',
            field=models.CharField(max_length=14),
        ),
    ]
