# Generated by Django 4.0.4 on 2022-09-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_alter_company_cnpj_alter_company_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=80)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Novo Registro',
                'verbose_name_plural': 'Novos Registros',
                'ordering': ('created',),
            },
        ),
    ]
